version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - postgres-network
      - postgres-test-network
    ports:
      - '4000:4000'

  postgres:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: T12password
      POSTGRES_USER: TUser
      POSTGRES_DB: todo_app
    networks:
      - postgres-network
    ports:
      - '5432:5432'

  postgres-test:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: T12password
      POSTGRES_USER: TUser
      POSTGRES_DB: todo_app
    networks:
      - postgres-test-network
    ports:
      - '5433:5432'

volumes:
  postgres-data:
  postgres-test-data:

networks:
  postgres-network:
  postgres-test-network:
